language: node_js

node_js:
  - node    # Current - Latest features
  - '10'    # LTS - Recommended for most users

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn run coverage:publish; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn run test; fi
  - yarn run lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    skip_cleanup: true
    api_key:
      secure: MI7DsZo7pT5Uh2i8eFGbljiBtTBcqTsvZDoUJuviRSwp+jfd2/QGPry3MbJ19hS47ut7T8IAdYutq2Y7tmAgWO2vg7Puwvg+x4WwABjUc7f1oUDPsEGKcU76pdraJZtcLwk1MojJ2c28bQehU2rCsQ+9DnDiMas98Ye88UMfyz2kveN5QNXzaNmhCebcm5P9MSjWV3fiob8uhzuo3P2JVoWaHB2slprSJUNLrDeH0QCcJtdVuGfhxfOwFa2dSWHQHKpaYRHtWQ+qvSo5J7NaA7Ae40YrXEtblVQnn7guPEwhiMna5hBD7CUIxc51XvKYQAr0Gc3oyJcjsJN0CJ13VPMlTu1wYcofd+jd/6xkI+tubcJJUP4cnXCmGxT2w3ueFJFsWW67vtgVsC9kITBs1OILJFbjW3Ddu8sHaH9NqcBN23WkKxvXd05/BpX1z5aj51nBn8cA+yuruGN40ahRaIIgC0dwzUdEX6RTI2KlC54r8Ncy1l1o8WTFDZnsx/vLh/hoexJf1+RvtVjKHr3Hv8/gNf9BRpbCyHK2ZNaoUJEu5rvf0qzTPfVnIvKewNJeIwdTIoNWgpj9HG4hjmX0sKnKeFa1FfzRUea2aXGN9iLXrFaqkz/NbU6XvzBD9W4xdEi2W6thJs07DqckxnZeAcPgpzighAQmOCoDVHZuT60=
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: azBrtMiMsakr1E3NuePq3dcBWKE4U1Q/UI0pRP0YQ9V98h3nHneH41Oi/l3mwvHBuFolgvAd+5llpRk/2i0hY8SoZG9EeP15PsBNasUzM+XNI/EnIPiPj2oBpxZ+QreXER3yRyZ4sLJMRhsBfehdxSMIsNp21QK+SAVeBZuhibHwHkym4euXnPUiUTEOfnQ0JgMUpC5Y5ErtT+V1xPsNbR+w5OCOtI/NbVlWi4ipFNTJZYUOYajLbsb+yyWaFWQco7w05F/pW0BCaBn2Ko3yCk1tDV2f5iUZ8gYQHHAA96lv96iibYJGmu30JkVsLPnleaNVE8wkWZ+Ju3jj+EYJgHqFzquhO/CUFzfUw+xN/ECE/wXQRDmkfAu3Va9soEGSb4xS/TnAsdj3pIvg0rJeQCx12jW58NC96hlTGPktyczJsPUcsAB9YJ4oFwDdsILWRUTMCQ82Fi1N5TQu9WOsS2wJYTv0xo5+uxld9xmUPg5KOUKvsf8RKOD6oANPkn++dSFqXK19p49mJvomm3RRN4GiTdaxZWXHbYCfPHz6gmV+feZzjIaN9zrdbS5se4/K/HcAqt134GCRd9qh71YZ5/Xro8lHUnkcCp8LA65PWKfwu0W/IS9PBDWRXHG0XaKgvVVjIoZhQ819wkbYpxS4k0c5lF7/459hdmUHnnc5h10=
    on:
      tags: true
