language: node_js

node_js:
  - node    # Current - Latest features
  - '10'    # LTS - Recommended for most users

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn run coverage:publish; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn run test; fi
  - yarn run lint

deploy:
  # - provider: npm
  #   email: mattias.kindborg@gmail.com
  #   skip_cleanup: true
  #   api_key:
  #     secure: oPpuhVrECIMWoR/WE+OjiQuAHFZ4buHL7qm13yrEIjlVgzhCOfrJt4Hkgw427pPQzDCcCwftjXLlZPO2AOf4obHSZeV3Ii3t4tJu1qhgM+oWW4VT1KL6/BBOFOh1slmK0ni9ZTwfPsA56zVu0qvD6xu+UiFDT8oO7pPYlMaBKmGAC/iWHrjj9uu5zdeQHM4gcBXJYWMMFB6m7xc2t8v0ajyU6bccz6RzqRQK8fZHFDKbmnHIfxK/0W76HQlK0og7GHi5QyjGlEMN2TFHa7O5UWAE21mDU1qMGwXYj9YhjsXgFHLMTX4HY99tTJwLbXyUeXL70yH8IFjnr4Id/6PvohYERdid6+pw7ic/7CxOHD8NPE6MMhbB+8byrr3rOR048zO0VlIz+k6NGTXfllNismbbVFm4QLLLBKv2nknto5ErUmmMpDMk3S2nItRXfdtlxFOpf4v1K982k5ktAmUZCQaCwj1Yd8bxNcAsXGkJgT3nHcmeu+r6o1acsuzIWuxyR5hbvDlCaqPnVXHgwAgIn7ImuuGUHeKhHKxrtwZb+P9bZ5EgSgJrskaUHfPV7swYJ4vsEyi+q0Ue6zFCei6frMwuKLVjFjGnd2YCbvTAO0T4FVNI6JlSM2TJbJeSZfz/ZEOXUnE5Bks23gP67L0Tc53cR7L2rKSrIBGQRl/wDt8=
  #   on:
  #     tags: true
  - provider: releases
    name: Temp release
    api_key:
      secure: azBrtMiMsakr1E3NuePq3dcBWKE4U1Q/UI0pRP0YQ9V98h3nHneH41Oi/l3mwvHBuFolgvAd+5llpRk/2i0hY8SoZG9EeP15PsBNasUzM+XNI/EnIPiPj2oBpxZ+QreXER3yRyZ4sLJMRhsBfehdxSMIsNp21QK+SAVeBZuhibHwHkym4euXnPUiUTEOfnQ0JgMUpC5Y5ErtT+V1xPsNbR+w5OCOtI/NbVlWi4ipFNTJZYUOYajLbsb+yyWaFWQco7w05F/pW0BCaBn2Ko3yCk1tDV2f5iUZ8gYQHHAA96lv96iibYJGmu30JkVsLPnleaNVE8wkWZ+Ju3jj+EYJgHqFzquhO/CUFzfUw+xN/ECE/wXQRDmkfAu3Va9soEGSb4xS/TnAsdj3pIvg0rJeQCx12jW58NC96hlTGPktyczJsPUcsAB9YJ4oFwDdsILWRUTMCQ82Fi1N5TQu9WOsS2wJYTv0xo5+uxld9xmUPg5KOUKvsf8RKOD6oANPkn++dSFqXK19p49mJvomm3RRN4GiTdaxZWXHbYCfPHz6gmV+feZzjIaN9zrdbS5se4/K/HcAqt134GCRd9qh71YZ5/Xro8lHUnkcCp8LA65PWKfwu0W/IS9PBDWRXHG0XaKgvVVjIoZhQ819wkbYpxS4k0c5lF7/459hdmUHnnc5h10=
    on:
      tags: true
