language: node_js

node_js:
  - node    # Current - Latest features
  - '10'    # LTS - Recommended for most users

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn run coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn run test; fi
  - yarn run lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    skip_cleanup: true
    api_key:
      secure: TKxChNxGfnpPGgZDCYek/jiF0vRfc5lYNFB3cuu8D25bwIwKO2ROfFDCryGq4bstvsko9YRzCYihgmzaF+HKitOU6wnLyMWO5Em9zKCmQJEQRUbFt1DFISF55d1Rnze1QqCZSo4uqY6QnpasgWCmnsOUF3dbsq7IrzwMNLl/z2FeWPhL4MJ4EMZuHa33qnMVYesBmpiPMzsQSB56oFGw7O/DTfQKALQ9xbZhcOcEDqYqhDzPRBBGSjAfQ9YOibS/so3uXVaTgCHEhROs5PvS3SJ5/oPHTyqeWaYXD12MtJCzpk+4FCwIgl1yxsOJDUlaU+jlcnDSfhkTgVeqABfxI+39266BcvpgRqjEBOMSfGbqSy2u4hMVr56+naefrbYhBJDlGQ+mt8BKGSQRcMvogfcfM6WK+97o2x0Ueibl0zverC8KXgoLRSxPvnhNkA4kt+I2F1G7tQxmSSKXWZTlXvQuvjFcM60AULom4skvPmicEUA7/gSvRp0yaXBH/pwMEIRiKpyCaYXkAdQtM6Ytc3vHApwBpbkdase44rOjmLkN9bMpkW3K+YAkoxCfXupxQYFva06zqzpKIDVKZg6nppo8M4evbvPS0trNiqnsEWMu80VCFOI2uAR8spdGQbDBKQB01yDQqvl6ePzP52F+ATOr4nbdedmqkMXYJ263p00=
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: FzsVknQykZb66AR0GToAgHSCPVsnRBySRmQNjWO7Au2++8x7f9XulmCTGTtCwC+p9R+NhhUVZOuv0NIqzqaWJNr7DAYw2daeBDRpvHeAxPbbKDq5/5ucYY03KGtKGgDg6V/P/H2sODAQcNSgmgQifULSPyEKh3fbS6me40U2f4XPZ1EAsPf12RZesSwxeRPAjcrrB5kofYvuyXVtUlIngRwDdqyVGLXh+EXM//odkkBr49n2d+0Yrlkb7yvZBQClJqEwNtNiM/Yuui8ffut2j9DhDQjxGcQK4f7/w6/IVCDvYKpxu2YXPT6ZYk3ksDwiXWlpZ5lFOuVwvM4ozgai+Qaw0fhHYi5W6tslbHJ3e9Q0eIscEc273EkVogTgmi9Rg0w8N049CKLnqG2W4P6wOs3u2GGElN7cDZlQgmwm4nwbfpFHNkTk60BDfzzOP/ajIk+8KHuKsTvXjrptUUROtKK3KrpTYRtMDn1qSpCCbonN8LXwEujlaE14BoRkMqtHeVsiSowE5cdEoD+Sm7p7ATG0hzCMU369HiRhmBYi1t1XxRhTMo3+u9hIONemE0dzPfEVOVw85WTOhpwmKH0m20ieHh1zlUIe20LAYfPo4+yu3IMxFN5POU/6DZnnrkqumMYbeEC7du+wouhDZPPSal6qSUDt0hQKchGvCqgYNdg=
    on:
      tags: true
