language: node_js

node_js:
  - "node"  # Current - Latest features
  - "7"
  - "6"     # LTS - Recommended for most users

matrix:
  fast_finish: true

install:
  - npm install

script:
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then npm run coverage:publish; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then npm run test; fi
  - npm run lint
